/*
# Mapunjan Sportswear complete Supabase setup

Run this entire file once in Supabase Dashboard > SQL Editor > New Query.

Creates admin_users, products, product_images, orders, order_items, delivery_locations, shop_settings, indexes, triggers, RLS, the product-images storage bucket, default delivery locations, default settings, and secure public order placement.
*/

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS admin_users (user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS products (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), team_name text NOT NULL, product_name text NOT NULL, category text NOT NULL CHECK (category IN ('Football','Basketball','Rugby','Athletics','Other')), season text NOT NULL, jersey_type text NOT NULL, description text, previous_price numeric(12,2) NOT NULL CHECK (previous_price >= 0), current_price numeric(12,2) NOT NULL CHECK (current_price >= 0), available_sizes text[] NOT NULL DEFAULT ARRAY['S','M','L','XL'], stock_quantity integer NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0), featured boolean NOT NULL DEFAULT false, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS product_images (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), product_id uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE, image_url text NOT NULL, storage_path text, is_primary boolean NOT NULL DEFAULT false, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS delivery_locations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL UNIQUE, sort_order integer NOT NULL DEFAULT 0, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS shop_settings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), shop_name text NOT NULL DEFAULT 'MAPUNJAN SPORTS WEAR', shop_address text NOT NULL DEFAULT 'Kakamega, Kenya', latitude numeric(10,7), longitude numeric(10,7), google_maps_url text, whatsapp_number text NOT NULL DEFAULT '+254798777231', business_phone text, business_description text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_number text NOT NULL UNIQUE, customer_name text NOT NULL, customer_phone text NOT NULL, delivery_location text NOT NULL, preferred_delivery_date date NOT NULL, preferred_delivery_time text NOT NULL, additional_instructions text, status text NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending','Confirmed','Preparing','Out for Delivery','Delivered','Cancelled')), total_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS order_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid NOT NULL REFERENCES orders(id) ON DELETE CASCADE, product_id uuid REFERENCES products(id) ON DELETE SET NULL, team_name text NOT NULL, product_name text NOT NULL, season text NOT NULL, jersey_type text NOT NULL, selected_size text NOT NULL, quantity integer NOT NULL CHECK (quantity BETWEEN 1 AND 100), unit_price numeric(12,2) NOT NULL CHECK (unit_price >= 0), created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS products_active_featured_idx ON products(active, featured);
CREATE INDEX IF NOT EXISTS products_category_idx ON products(category);
CREATE INDEX IF NOT EXISTS product_images_product_idx ON product_images(product_id, sort_order);
CREATE INDEX IF NOT EXISTS orders_status_created_idx ON orders(status, created_at DESC);
CREATE INDEX IF NOT EXISTS order_items_order_idx ON order_items(order_id);
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;
DROP TRIGGER IF EXISTS products_updated_at ON products; CREATE TRIGGER products_updated_at BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS delivery_locations_updated_at ON delivery_locations; CREATE TRIGGER delivery_locations_updated_at BEFORE UPDATE ON delivery_locations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS shop_settings_updated_at ON shop_settings; CREATE TRIGGER shop_settings_updated_at BEFORE UPDATE ON shop_settings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS orders_updated_at ON orders; CREATE TRIGGER orders_updated_at BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE FUNCTION is_admin() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM admin_users WHERE user_id = auth.uid()); $$;
REVOKE ALL ON FUNCTION is_admin() FROM PUBLIC; GRANT EXECUTE ON FUNCTION is_admin() TO anon, authenticated;
CREATE OR REPLACE FUNCTION next_order_number() RETURNS text LANGUAGE plpgsql AS $$ DECLARE today text := to_char(current_date, 'YYYYMMDD'); next_number integer; BEGIN SELECT COALESCE(MAX((substring(order_number from 14))::integer), 0) + 1 INTO next_number FROM orders WHERE order_number LIKE 'MAP-' || today || '-%'; RETURN 'MAP-' || today || '-' || lpad(next_number::text, 4, '0'); END; $$;
CREATE OR REPLACE FUNCTION place_public_order(p_customer_name text,p_customer_phone text,p_delivery_location text,p_preferred_delivery_date date,p_preferred_delivery_time text,p_additional_instructions text,p_product_id uuid,p_size text,p_quantity integer) RETURNS json LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ DECLARE product_row products%ROWTYPE; new_order orders%ROWTYPE; total numeric(12,2); BEGIN IF length(trim(p_customer_name)) < 2 OR length(trim(p_customer_phone)) < 7 OR p_quantity IS NULL OR p_quantity < 1 OR p_quantity > 100 THEN RAISE EXCEPTION 'Invalid order details'; END IF; SELECT * INTO product_row FROM products WHERE id = p_product_id AND active = true FOR UPDATE; IF product_row.id IS NULL OR product_row.stock_quantity < p_quantity OR NOT (p_size = ANY(product_row.available_sizes)) THEN RAISE EXCEPTION 'Product is unavailable'; END IF; total := product_row.current_price * p_quantity; INSERT INTO orders(order_number,customer_name,customer_phone,delivery_location,preferred_delivery_date,preferred_delivery_time,additional_instructions,total_amount) VALUES(next_order_number(),trim(p_customer_name),trim(p_customer_phone),trim(p_delivery_location),p_preferred_delivery_date,trim(p_preferred_delivery_time),nullif(trim(p_additional_instructions),''),total) RETURNING * INTO new_order; INSERT INTO order_items(order_id,product_id,team_name,product_name,season,jersey_type,selected_size,quantity,unit_price) VALUES(new_order.id,product_row.id,product_row.team_name,product_row.product_name,product_row.season,product_row.jersey_type,p_size,p_quantity,product_row.current_price); UPDATE products SET stock_quantity = stock_quantity - p_quantity WHERE id = product_row.id; RETURN json_build_object('order_id',new_order.id,'order_number',new_order.order_number,'total_amount',total); END; $$;
REVOKE ALL ON FUNCTION place_public_order(text,text,text,date,text,text,uuid,text,integer) FROM PUBLIC; GRANT EXECUTE ON FUNCTION place_public_order(text,text,text,date,text,text,uuid,text,integer) TO anon, authenticated;
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY; ALTER TABLE products ENABLE ROW LEVEL SECURITY; ALTER TABLE product_images ENABLE ROW LEVEL SECURITY; ALTER TABLE orders ENABLE ROW LEVEL SECURITY; ALTER TABLE order_items ENABLE ROW LEVEL SECURITY; ALTER TABLE delivery_locations ENABLE ROW LEVEL SECURITY; ALTER TABLE shop_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS admin_users_select_admin ON admin_users; CREATE POLICY admin_users_select_admin ON admin_users FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS products_public_read ON products; CREATE POLICY products_public_read ON products FOR SELECT TO anon, authenticated USING (active = true OR is_admin());
DROP POLICY IF EXISTS products_admin_insert ON products; CREATE POLICY products_admin_insert ON products FOR INSERT TO authenticated WITH CHECK (is_admin());
DROP POLICY IF EXISTS products_admin_update ON products; CREATE POLICY products_admin_update ON products FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS products_admin_delete ON products; CREATE POLICY products_admin_delete ON products FOR DELETE TO authenticated USING (is_admin());
DROP POLICY IF EXISTS images_public_read ON product_images; CREATE POLICY images_public_read ON product_images FOR SELECT TO anon, authenticated USING (EXISTS (SELECT 1 FROM products WHERE products.id = product_images.product_id AND (products.active = true OR is_admin())));
DROP POLICY IF EXISTS images_admin_insert ON product_images; CREATE POLICY images_admin_insert ON product_images FOR INSERT TO authenticated WITH CHECK (is_admin());
DROP POLICY IF EXISTS images_admin_update ON product_images; CREATE POLICY images_admin_update ON product_images FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS images_admin_delete ON product_images; CREATE POLICY images_admin_delete ON product_images FOR DELETE TO authenticated USING (is_admin());
DROP POLICY IF EXISTS orders_admin_read ON orders; CREATE POLICY orders_admin_read ON orders FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS orders_admin_update ON orders; CREATE POLICY orders_admin_update ON orders FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS order_items_admin_read ON order_items; CREATE POLICY order_items_admin_read ON order_items FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS locations_public_read ON delivery_locations; CREATE POLICY locations_public_read ON delivery_locations FOR SELECT TO anon, authenticated USING (active = true OR is_admin());
DROP POLICY IF EXISTS locations_admin_insert ON delivery_locations; CREATE POLICY locations_admin_insert ON delivery_locations FOR INSERT TO authenticated WITH CHECK (is_admin());
DROP POLICY IF EXISTS locations_admin_update ON delivery_locations; CREATE POLICY locations_admin_update ON delivery_locations FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS locations_admin_delete ON delivery_locations; CREATE POLICY locations_admin_delete ON delivery_locations FOR DELETE TO authenticated USING (is_admin());
DROP POLICY IF EXISTS settings_public_read ON shop_settings; CREATE POLICY settings_public_read ON shop_settings FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS settings_admin_insert ON shop_settings; CREATE POLICY settings_admin_insert ON shop_settings FOR INSERT TO authenticated WITH CHECK (is_admin());
DROP POLICY IF EXISTS settings_admin_update ON shop_settings; CREATE POLICY settings_admin_update ON shop_settings FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS settings_admin_delete ON shop_settings; CREATE POLICY settings_admin_delete ON shop_settings FOR DELETE TO authenticated USING (is_admin());
INSERT INTO delivery_locations(name,sort_order) VALUES ('Lurambi',1),('Mwiyala',2),('T-Zone',3),('MMUST',4),('KEFINCO',5),('Milimani',6),('Koromatangi',7),('Sichirayii',8),('Stage Mandazi',9) ON CONFLICT (name) DO NOTHING;
INSERT INTO shop_settings(shop_name,shop_address,whatsapp_number,business_description) SELECT 'MAPUNJAN SPORTS WEAR','Kakamega, Kenya','+254798777231','Original team kits and sportswear.' WHERE NOT EXISTS (SELECT 1 FROM shop_settings);
INSERT INTO storage.buckets(id,name,public) VALUES ('product-images','product-images',true) ON CONFLICT (id) DO NOTHING;
DROP POLICY IF EXISTS product_images_public_read ON storage.objects; CREATE POLICY product_images_public_read ON storage.objects FOR SELECT TO anon, authenticated USING (bucket_id = 'product-images');
DROP POLICY IF EXISTS product_images_admin_insert ON storage.objects; CREATE POLICY product_images_admin_insert ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'product-images' AND is_admin());
DROP POLICY IF EXISTS product_images_admin_update ON storage.objects; CREATE POLICY product_images_admin_update ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'product-images' AND is_admin()) WITH CHECK (bucket_id = 'product-images' AND is_admin());
DROP POLICY IF EXISTS product_images_admin_delete ON storage.objects; CREATE POLICY product_images_admin_delete ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'product-images' AND is_admin());
